<?xml version="1.0" encoding="UTF-8"?><testrun name="Tests" project="PhonyList" tests="15" started="15" failures="1" errors="0" ignored="0">
  <testsuite name="system.Tests" time="0.016">
    <testcase name="size_empty" classname="system.Tests" time="0.0"/>
    <testcase name="empty_true" classname="system.Tests" time="0.0"/>
    <testcase name="add_smallList" classname="system.Tests" time="0.0"/>
    <testcase name="add_emptyList" classname="system.Tests" time="0.0"/>
    <testcase name="remove_list" classname="system.Tests" time="0.0"/>
    <testcase name="remove_vide" classname="system.Tests" time="0.0"/>
    <testcase name="size_notEmpty" classname="system.Tests" time="0.0"/>
    <testcase name="set_toFar" classname="system.Tests" time="0.0"/>
    <testcase name="get_add_list" classname="system.Tests" time="0.0"/>
    <testcase name="get_toFar" classname="system.Tests" time="0.0"/>
    <testcase name="set_list" classname="system.Tests" time="0.016">
      <failure>java.lang.AssertionError: expected:&lt;15&gt; but was:&lt;4&gt;&#13;
	at org.junit.Assert.fail(Assert.java:88)&#13;
	at org.junit.Assert.failNotEquals(Assert.java:743)&#13;
	at org.junit.Assert.assertEquals(Assert.java:118)&#13;
	at org.junit.Assert.assertEquals(Assert.java:555)&#13;
	at org.junit.Assert.assertEquals(Assert.java:542)&#13;
	at system.Tests.set_list(Tests.java:185)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="set_vide" classname="system.Tests" time="0.0"/>
    <testcase name="empty_false" classname="system.Tests" time="0.0"/>
    <testcase name="get_vide" classname="system.Tests" time="0.0"/>
    <testcase name="remove_eAbsent" classname="system.Tests" time="0.0"/>
  </testsuite>
</testrun>
